spring.application.name=lovable

#Database Properties
spring.datasource.url=jdbc:mysql://mysql:3306/lovable
spring.datasource.username=appuser
spring.datasource.password=Password@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect