spring.application.name=lovable
spring.datasource.url=jdbc:postgresql://localhost:9000/lovable
spring.datasource.username=appuser
spring.datasource.password=Password@123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Force Hibernate to create tables if they don't exist
spring.jpa.hibernate.ddl-auto=update
# Optional: See the SQL in the console to confirm table creation
spring.jpa.show-sql=true

